version: "3"
services:
  jupyter:
    build: .
    volumes:
      - $PWD:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
